version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--dir", "/data"]

  task-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: ["python", "main.py"]